all:
	@tar xf autograde.tar
	@cp handin.* grader/submission.s
	@python3 grader/wrapper.py


clean: 
	-rm grader/error.txt
	-rm grader/concatErrors.txt
	-rm grader/input.txt
	-rm grader/output.txt
	-rm grader/submission.s
	-rm grader/concat.s







