# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestLayout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from UserInputRow import Ui_UserInputRow
from PyQt5 import QtCore, QtGui, QtWidgets
from collapsibleBox import CollapsibleBox
#from UserInputRow import Ui_UserInputRow
from classes import *


class Test(QtWidgets.QWidget): 
    def __init__(self): 
        super(QtWidgets.QWidget, self).__init__() 
        self.setupUi()

    def setupUi(self):
        self.setObjectName("test") 
        self.setMinimumWidth(725)
        self.verticalLayout = QtWidgets.QVBoxLayout(self) 
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(0)
        self.HidingBox=CollapsibleBox("Test")
        self.verticalLayout.addWidget(self.HidingBox)
        self.TopRow=TestTopRow()
        self.HidingBox.addWidget(self.TopRow)
        self.allUserInput=CollapsibleBox("User Input",self.HidingBox)
        self.DataInput=CollapsibleBox("Data Input",self.HidingBox)
        self.InputRegisters=CollapsibleBox("Input Registers",self.HidingBox)
        self.OutputRegisters=CollapsibleBox("Output Registers",self.HidingBox)


        Addbutton = QtWidgets.QPushButton()
        Addbutton.pressed.connect(self.addUserInputRow)
        self.allUserInput.addWidget(Addbutton)
        self.allUserInput.addWidget(Ui_UserInputRow())
        self.DataInput.addWidget(QtWidgets.QPushButton())
        self.DataInput.addWidget(QtWidgets.QPushButton())
        self.DataInput.addWidget(QtWidgets.QPushButton())
        self.InputRegisters.addWidget(QtWidgets.QPushButton())
        self.InputRegisters.addWidget(QtWidgets.QPushButton())
        self.InputRegisters.addWidget(QtWidgets.QPushButton())
        self.InputRegisters.addWidget(QtWidgets.QPushButton())
        self.OutputRegisters.addWidget(QtWidgets.QPushButton())
        self.OutputRegisters.addWidget(QtWidgets.QPushButton())
    
        


        self.verticalLayout.addStretch()
        self.retranslateUi() 
    #TODO make the add user input button work
    def addUserInputRow(self):
        row=UserInputRow()
        self.allUserInput.addWidget(row)
        
        #self.allUserInput.setself.HidingBox.geometry().height()

    def retranslateUi(self): 
        pass
         