# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserInputRow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserInputRow(object):
    def setupUi(self, UserInputRow):
        UserInputRow.setObjectName("UserInputRow")
        UserInputRow.resize(700, 31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UserInputRow.sizePolicy().hasHeightForWidth())
        UserInputRow.setSizePolicy(sizePolicy)
        UserInputRow.setMinimumSize(QtCore.QSize(0, 0))
        UserInputRow.setMaximumSize(QtCore.QSize(700, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(UserInputRow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(UserInputRow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 23))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 18pt \"Sans Serif\";\n"
"text-decoration: line-through;\n"
"text-decoration: line-through;\n"
"color: rgb(255, 0, 4);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(UserInputRow)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)

        self.retranslateUi(UserInputRow)
        QtCore.QMetaObject.connectSlotsByName(UserInputRow)

    def retranslateUi(self, UserInputRow):
        pass
